version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    container_name: chat-postgres
    ports:
      - "5440:5432"
    environment: 
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: chat-redis
    environment:
      REDIS_USERNAME: hello
      REDIS_PASSWORD: local
    ports:
      - "6380:6379"
